### ISSUE TITLE
s_playtable loop arg not implemented

### ISSUE THREAD

**Issue by danomatika** [rjdj/rjlib#21]
As far as I can tell, the loop argument mentioned in the s_playtable & s_playtable2 help patches is not implemented. Or, at least, the loop inlet deep in the patch isn't connected to anything. I ask because I'm wrapping up a looping sample player (thinking of calling it s_looptable).

If the loop arg is just a leftover, I can remove it come the helps etc and add that commit to my current PR.

**Comment by footils** [comment]
Hi Dan,

yes, it was indeed never implemented, so it can be removed.

Ciao
-- 
Frank

On Sun, Nov 01, 2015 at 11:38:56PM -0800, Dan Wilcox wrote:
> As far as I can tell, the loop argument mentioned in the s_playtable & s_playtable2 help patches is not implemented. Or, at least, the loop inlet deep in the patch isn't connected to anything. I ask because I'm wrapping up a looping sample player (thinking of calling it s_looptable).
> 
> If the loop arg is just a leftover, I can remove it come the helps etc and add that commit to my current PR.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/rjdj/rjlib/issues/21

-- 
 Frank Barknecht                                     _ ______footils.org__

**Comment by danomatika** [comment]
Ah ok. Will do.

Also, any thoughts on using [array size] to know the stopping point? I think it's new as of vanilla 0.46 so might cause issues with people still using extended, but not libpd. It's working very nicely for [u_loopsample] (almost done).

**Comment by footils** [comment]
Hi,

I think, there should be a clean versioning cut first, like tagging (and
releasing?) some kind of rjlib 1.0 as it is, then moving on to all the nice new
objects of the latest vanilla. A lot of things could be made much easier with these.

Ciao
-- 
Frank

On Mon, Nov 02, 2015 at 02:33:49AM -0800, Dan Wilcox wrote:
> Ah ok. Will do.
> 
> Also, any thoughts on using [array size] to know the stopping point? I think it's new as of vanilla 0.46 so might cause issues with people still using extended, but not libpd. It's working very nicely for [u_loopsample] (almost done).
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/rjdj/rjlib/issues/21#issuecomment-152982862

-- 
 Frank Barknecht                                     _ ______footils.org__

**Comment by danomatika** [comment]
I'd say it's safe to tag now. Everything is pretty much stable. Most issues I've been seeing as little documentation things. It's mostly updates & additions going forward (i.e. I'd like to see the default sample rate moved to 44.1).
